### PR TITLE
One better

### PR DESCRIPTION
**Pull request by jonnolen**
you're welcome.

### CODE REVIEW

**Comment by jonnolen** [comment]
i may have messed up.  hemorrhoid should be a parallel command to crap instead of a replacment.  and I screwed up the installs for the destination.. .those should have been excluded.

**Comment by jonnolen** [comment]
it forces the push through even if there is  tree mismatch on the remote.

**Comment by jonnolen** [comment]
i've updated the pull request to fix install issues and re-add crap.  hemorrhoid is a parallel optional command.

I've done zero testing.

**Comment by benlipp** [comment]
I don't really see the need for a parallel command. Because it does the same thing, an alias can be added for the same functionality.

**Comment by jonnolen** [comment]
it doesn't do the same thing... it force pushes instead of vanilla safe push.

**Comment by benlipp** [comment]
Added `crap hemorrhoid` to force a push.

**Comment by jonnolen** [comment]
:golf: :clap:

**Pull request closed without merging**
